Repository hak5/usbrubberducky-payloads, pull requests merged in 2023-06, with the labels that each got.

#291 Exfiltrate Photos Through Shell
  payloads/library/exfiltration/ExfiltratePhotosThroughShell/README.md
  payloads/library/exfiltration/ExfiltratePhotosThroughShell/payload.txt
  payloads/library/exfiltration/ExfiltratePhotosThroughShell/script.sh
Labels: suggestions added

#285 Standard Phishing Campaign - Linux
  payloads/library/phishing/StandardPhishingCampaign_Linux/DuckyScript-DOC.md
  payloads/library/phishing/StandardPhishingCampaign_Linux/README.md
  payloads/library/phishing/StandardPhishingCampaign_Linux/Script-DOC.md
  payloads/library/phishing/StandardPhishingCampaign_Linux/Script.zip
  payloads/library/phishing/StandardPhishingCampaign_Linux/login.html
  payloads/library/phishing/StandardPhishingCampaign_Linux/payload.txt
  payloads/library/phishing/StandardPhishingCampaign_Linux/script.js
Labels: pending requested changes

#288 Phishing Payload Using kdialog Standardized
  payloads/library/phishing/StandardPhishingPayloadUsingKdialog_Linux/README.md
  payloads/library/phishing/StandardPhishingPayloadUsingKdialog_Linux/payload.txt
Labels: pending further info

#300 Continuos Print In Terminal
  payloads/library/prank/Continuos Print In Terminal/README.md
  payloads/library/prank/Continuos Print In Terminal/payload.txt
  payloads/library/prank/Continuos Print In Terminal/script.py
Labels: pending further info

#309 Create windows_repair.txt
  payloads/library/prank/windows_repair.txt
Labels: pending requested changes

#311 Send Email Through Thunderbird - Windows 11 && Ubuntu 23.04 tested
  payloads/library/execution/SendEmailThroughThunderbird/README.md
  payloads/library/execution/SendEmailThroughThunderbird/payload.txt
Labels: pending requested changes

#312 Full-Screen Banner Joke
  payloads/library/prank/Full-ScreenBannerJoke/README.md
  payloads/library/prank/Full-ScreenBannerJoke/payload.txt
  payloads/library/prank/Full-ScreenBannerJoke/script.py
Labels: pending requested changes

#322 Commit Horsd payload
  payloads/library/prank/Horsd/README.md
  payloads/library/prank/Horsd/horsd.ps1
  payloads/library/prank/Horsd/payload.txt
Labels: pending requested changes
