Repository hak5/usbrubberducky-payloads, pull requests merged in 2024-01, with the labels that each got.

#380 initial commit of cloud exfil script
  payloads/library/exfiltration/ExfiltrateCloudCreds/README.md
  payloads/library/exfiltration/ExfiltrateCloudCreds/payload.txt
Labels: pending further info

#373 Persistent Keylogger - Telegram Based
  payloads/library/execution/Persistent_Keylogger-Telegram_Based/README.md
  payloads/library/execution/Persistent_Keylogger-Telegram_Based/connection.py
  payloads/library/execution/Persistent_Keylogger-Telegram_Based/payload.txt
Labels: pending requested changes

#372 Persistent Reverse Shell - Telegram Based
  payloads/library/execution/Persistent_Reverse_Shell-Telegram_Based/README.md
  payloads/library/execution/Persistent_Reverse_Shell-Telegram_Based/connection.py
  payloads/library/execution/Persistent_Reverse_Shell-Telegram_Based/payload.txt
Labels: pending requested changes

#371 Telegram Persistent Connection Linux
  payloads/library/execution/Telegram_Persistent_Connection_Linux/README.md
  payloads/library/execution/Telegram_Persistent_Connection_Linux/connection.py
  payloads/library/execution/Telegram_Persistent_Connection_Linux/payload.txt
Labels: pending requested changes

#337 Export all saved certificates with Adobe Reader
  payloads/library/exfiltration/Export_all_saved_certificates_with_Adobe_Reader/README.md
  payloads/library/exfiltration/Export_all_saved_certificates_with_Adobe_Reader/payload.txt
Labels: pending requested changes

#338 Exfiltrates the entire database of the Notion client
  payloads/library/exfiltration/Exfiltrates_the_entire_database_of_the_Notion_client/README.md
  payloads/library/exfiltration/Exfiltrates_the_entire_database_of_the_Notion_client/payload.txt
Labels: pending requested changes

#339 Tree Structure Of The Operating System
  payloads/library/exfiltration/Tree_structure_of_the_operating_system/1.png
  payloads/library/exfiltration/Tree_structure_of_the_operating_system/README.md
  payloads/library/exfiltration/Tree_structure_of_the_operating_system/payload.txt
Labels: pending requested changes

#340 Uninstall A Specific App On Windows Through Control Panel
  payloads/library/execution/Uninstall_A_Specific_App_On_Windows_Through_Control_Panel/README.md
  payloads/library/execution/Uninstall_A_Specific_App_On_Windows_Through_Control_Panel/payload.txt
Labels: pending requested changes

#341 Create And Exfiltrate A Webhook Of Discord
  payloads/library/exfiltration/Create_And_Exfiltrate_A_Webhook_Of_Discord/README.md
  payloads/library/exfiltration/Create_And_Exfiltrate_A_Webhook_Of_Discord/payload.txt
Labels: pending further info, pending requested changes

#342 Try To Catch Me
  payloads/library/prank/Try_To_Catch_Me/README.md
  payloads/library/prank/Try_To_Catch_Me/example.gif
  payloads/library/prank/Try_To_Catch_Me/payload.txt
  payloads/library/prank/Try_To_Catch_Me/script.py
Labels: pending further info

#346 Send Messages In Discord Channel-Server
  payloads/library/execution/Send_Messages_In_Discord_Channel-Server/README.md
  payloads/library/execution/Send_Messages_In_Discord_Channel-Server/assets/1.png
  payloads/library/execution/Send_Messages_In_Discord_Channel-Server/assets/2.png
  payloads/library/execution/Send_Messages_In_Discord_Channel-Server/payload.txt
Labels: pending requested changes

#347 Install And Run Any Arbitrary Executable - No Internet And Root Needed
  payloads/library/execution/Install_And_Run_Any_Arbitrary_Executable-No_Internet_And_Root_Needed/README.md
  payloads/library/execution/Install_And_Run_Any_Arbitrary_Executable-No_Internet_And_Root_Needed/assets/README.md
  payloads/library/execution/Install_And_Run_Any_Arbitrary_Executable-No_Internet_And_Root_Needed/assets/convert_to_hex.py
  payloads/library/execution/Install_And_Run_Any_Arbitrary_Executable-No_Internet_And_Root_Needed/assets/example.hex
  payloads/library/execution/Install_And_Run_Any_Arbitrary_Executable-No_Internet_And_Root_Needed/assets/example.py
  payloads/library/execution/Install_And_Run_Any_Arbitrary_Executable-No_Internet_And_Root_Needed/payload.txt
Labels: pending requested changes
