Repository hak5/usbrubberducky-payloads, pull requests merged in 2024-06, with the labels that each got.

#444 Dump Windows Memory Through ProcDump
  payloads/library/exfiltration/Dump_Windows_Memory_Through_ProcDump/README.md
  payloads/library/exfiltration/Dump_Windows_Memory_Through_ProcDump/payload.txt
Labels: pending requested changes

#443 This Damn Shell Doesn't Work, SO SAD! :C
  payloads/library/prank/This_damn_shell_doesn_t_work___so_sad!/1.gif
  payloads/library/prank/This_damn_shell_doesn_t_work___so_sad!/README.md
  payloads/library/prank/This_damn_shell_doesn_t_work___so_sad!/payload.txt
Labels: pending requested changes

#441 Wino willy BeEF Injection
  payloads/library/execution/BeEF_Injection/payload.txt
Labels: pending requested changes, awaiting response

#442 adding new ExfiltrateSSHKeys payload
  payloads/library/exfiltration/ExfiltrateSSHKeys/README.md
  payloads/library/exfiltration/ExfiltrateSSHKeys/payload.txt
Labels: pending requested changes

#453 Prank In The Middle - Thunderbird
  payloads/library/prank/Prank_In_The_Middle_Thunderbird/README.md
  payloads/library/prank/Prank_In_The_Middle_Thunderbird/payload.txt
Labels: pending requested changes

#411 Patch ducky logger
  payloads/library/credentials/DuckyLogger/payload.txt
  payloads/library/credentials/DuckyLogger2/payload.txt
Labels: requires review from author
